version: '3.8' # Utilise une version récente du format Docker Compose

services:
  # Votre Microservice Spring Boot
  mon-microservice:
    # L'image à utiliser, tirée de votre Docker Hub
    # Remplacez 0xbones1 par votre nom d'utilisateur Docker Hub si nécessaire
    image: 0xbones1/testing-is-everything:latest

    # Mappe le port 8080 du conteneur au port 8080 de votre machine locale
    ports:
      - "8080:8080"

    # Redémarre toujours le conteneur en cas d'échec
    restart: always

# Pour lancer l'application (CD) :
# 1. docker compose pull
# 2. docker compose up -d